### ISSUE TITLE
Nested environment when installing in development mode

### ISSUE THREAD

**Issue by gdarkwah** [UW-SASWE/RAT#35]
When you follow the [documentation](https://rat-satellitedams.readthedocs.io/en/latest/Development/DevelopmentGuide/) to install RAT in development mode, mamba creates a nested `rat-env`. Is it possible to modify the `environment.yml` file so that instead of creating a whole new environment, it will only install the required packages?

**Comment by pritamd47** [comment]
Thanks @gdarkwah ! This commit a1536d35e4f05b8c3c697540419bb34e40ad287b removes the environment name from the `environment.yml` file, which should solve this issue.
