### ISSUE TITLE
Step 9 uses station file (routing input) to generate list of reservoirs (gee_basin_params)

### ISSUE THREAD

**Issue by pritamd47** [UW-SASWE/RAT#51]
Step-9 was using the station file generated in `ro/pars` to generate the list of reservoirs to convert to final outputs (`gee_basin_params`). The #39 PR made it so that each reservoir will have the `pars` directory in their workspace directory instead of a single directory under `ro/pars`. This is breaking step-9 and the `gee_basin_params` is not being generated

https://github.com/UW-SASWE/RAT/blob/f447d5e199085f773ae6faa8224be2786e2e98a7/src/rat/rat_basin.py#L536-L539

**Comment by SanchitMinocha** [comment]
Resolved by #55.

**Comment by SanchitMinocha** [comment]
Resolved by #55.
